MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '.resnet50-19c8e357.pth'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  ARCH : 'VideoReID'
#   LOCAL_RANK : [0,1]

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  SEQ_LEN: 8
  NAME : 'Mars'
  ROOT_DIR : '/home/omnisky/LXH/data/Mars'
  TRAIN_SAMPLE_METHOD : "Random_interval"
  TEST_SAMPLE_METHOD : "Begin_interval"

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  SEQS_PER_BATCH: 32

  BASE_LR: 0.00035 # 0.0001
  MAX_EPOCHS: 400 # 500
  STEPS: [70, 140, 210, 280, 350, 400] ##[70, 140, 210, 310, 410] ## [50, 100, 150, 200, 300, 400] ##
  GAMMA: 0.3  # 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 20
  EVAL_PERIOD: 50

TEST:
  SEQS_PER_BATCH: 32
  RE_RANKING: 'no'
  WEIGHT: "path"
  IS_CAT: 'yes'

  FEAT_NORM: 'yes'
  CAlCULATION_METHOD: 'cosine'


OUTPUT_DIR: '/home/omnisky/LXH/projects/log_ViT'

